#!/bin/bash
bundle exec rake db:drop
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake db:seed --trace
bundle exec rake db:create RAILS_ENV=test
bundle exec rake db:migrate RAILS_ENV=test
COVERAGE=true bundle exec rake
bundle exec script/doc
bundle exec rails s
